### ISSUE TITLE
Duplicate of #1

### ISSUE THREAD

**Issue by BoogieHasFun** [NotAika/SmoothedController#2] opened 2021-09-03 23:28 UTC
when smooth controller has max settings, then you quit and come back the controller cant move, might be in only in health and safety.

**Comment by uslashdeleted** [comment] 2021-09-09 11:35
This issue is a duplicate of #1

**Closed** 2021-09-09 19:53 UTC

**Comment by BoogieHasFun** [comment] 2021-09-09 19:54
#1
